### ISSUE TITLE
"String or binary data would be truncated" error while inserting #query_store_plan

### ISSUE THREAD

**Issue by shabeker** [erikdarlingdata/DarlingData#107]
I get the above error when running the SP on my database. Checking the code, the field all_plan_ids in #query_store_plan is declared varchar(1000), but the FOR XML that concatenates the values for this field is varchar(MAX). If I change the declaration of all_plan_ids to varchar(MAX), the SP runs fine.

**Comment by erikdarlingdata** [comment]
Jeez, I figured I set that column size on the high side, too.
