### ISSUE TITLE
sp_QuickieStore Execution errors

### ISSUE THREAD

**Issue by troydtech** [erikdarlingdata/DarlingData#109]
**Version of the script**
sp_QuickieStore 2021
Executing on SQL Server 2017 Standard

**What is the current behavior?**
Compiles ok but getting the following error when executing with any parameters

Msg 50000, Level 11, State 1, Procedure sp_QuickieStore, Line 4300 [Batch Start Line 0]
error while (null)
offending query:
(null)
Msg 50000, Level 11, State 1, Procedure sp_QuickieStore, Line 76 [Batch Start Line 0]
This procedure only runs on supported versions of SQL Server

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute with any variables flags, etc or debug

**What is the expected behavior?**
Program runs without error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2017 on Windows Server 2016

**Comment by erikdarlingdata** [comment]
It sounds like your server isn't patched past CU3. Can you confirm the version number?

**Comment by troydtech** [comment]
14.0.1000.169

**Comment by erikdarlingdata** [comment]
Yep, that's RTM. Time to [get patching](https://sqlserverupdates.com/sql-server-2017-updates/). You're on ~4 year old bits there.

**Comment by troydtech** [comment]
Thanks, I will be dealing with many versions of servers across customer base.   What specifically are the patch levels required for each version from 2016+?  I didn't see anything specific.

This was SQL 2017 so assumed that the base RTM version here would be better than 2016 and still execute.

**Comment by erikdarlingdata** [comment]
For 2016 it's SP2, for 2017 it's CU3. I didn't document that initially because the bits are so old.

**Comment by troydtech** [comment]
Thanks for the info!  Just checked and it does work fine on a system with patches up to date.   Might want to add some release notes to that effect but it looks like a nice tool to have in the toolbox.    Have a great day.   Issue is resolved.
