### ISSUE TITLE
sp_HumanEvents: Add functionality to write ring buffer data off to tables

### ISSUE THREAD

**Issue by erikdarlingdata** [erikdarlingdata/DarlingData#11]
Would need a mechanism sort of like `sp_AllNightLog` to grab from active sessions and push to tables. 

What'd have to happen:
- Sessions would need to be created with `@keepalive = 1`
- That would prefix the session type with "permanent" or something
- A separate code path would run and grab new data (which means I'd need a logging mechanism to keep track of when the last collection was) from any XE session with permanentHumanEvents in the name

**Comment by ronaldgithub** [comment]
That would be nice!

**Comment by erikdarlingdata** [comment]
A lot of this is done.

Stuff I need to do: 
 * change the startup state to on for events that will get logged to tables, or add code to start them up when we go looking for jobs to log to tables
 * add delete retention
 * create views that make the raw data logged to tables more helpful
 * maybe get that server diagnostics stuff
