### ISSUE TITLE
Support needed for large amounts of RAM

### ISSUE THREAD

**Issue by ShaunJStu** [erikdarlingdata/DarlingData#116]
https://github.com/erikdarlingdata/DarlingData/blob/a468b03e18d9b3d0253a74aa6c6bad556df43150/sp_PressureDetector/sp_PressureDetector.sql#L161

I have a large amount of memory on my server (about 1 TB) and this was giving an "arithmetic overflow error converting number to data type numeric" error. Changed DECIMAL(5,2) to DECIMAL(6,2) in three places in this query and that fixed it.

**Comment by erikdarlingdata** [comment]
Were you going to create a pull request for this?

**Comment by ShaunJStu** [comment]
I have zero experience with GitHub and pull requests in general, so I'm guessing the answer will end up being no.

**Comment by erikdarlingdata** [comment]
This is exactly why I have templates for people to fill out when they open issues 😃
