### ISSUE TITLE
Saving sp_QuickieStore output for reporting/trending/analyzing?

### ISSUE THREAD

**Issue by AngryRhetoric** [erikdarlingdata/DarlingData#123]
Compliments: 
First things first, I love this stored procedure, thank you! It has been so handy for performance troubleshooting when I need QueryStore information as a result-set without having to muck with the QueryStore DMV's.  

The problem: 
You've made it So handy, my boss wants to retain top slow queries (found in QueryStore) for trending, long-term analysis. 
I thought: rather than reinvent the wheel, I'll just use the nice wheel you've made here to capture the top costliest 10 queries from the past 24 hours and the basic (non-expert-mode) output.

I tried to insert the output of this stored procedure into a (temp) table, but SQL complains about not allowing nested "insert into ... exec" statements since you already use "insert into #table sp_executesql @sql" inside sp_QuickieStore.
This would have prevented me from having to mess with any code inside the procedure.

Specific error from SQL Server:
Msg 8164, Level 16, State 1, Procedure sp_QuickieStore, Line 1684 [Batch Start Line 2]
An INSERT EXEC statement cannot be nested.

Potential solution:
I apologize if there's a better way to do this, or if it's already been handled in some other way, but I'm envisioning a new parameter called @Reporting_Mode that allows your temp tables to instead be permanent tables that are truncated after each run of the proc and stored in the same database container.  You could then select from those tables and do what you want with the results.

I had to do this for a similar project (stored procedure) and this turned out to be the simplest solution I could think of (not saying much haha).

I would be happy to take a stab at forking your code (does that sound evil?) and attempting this new feature, but wanted your thoughts on this in case I'm barking up the wrong tree.

Thanks!

-Kevin McD

**Comment by erikdarlingdata** [comment]
Hi Kevin!

Thanks, yeah. Appreciate the kind words. 

This is definitely a long-term item I'd been considering, but trying to scope it correctly. Since this proc can produce multiple result sets, I was toying with the idea of being able to export all of them aside from the main output. There's also the looming specter of someone wanting to push the data across servers 😬

Since you're the first person to ask for it -- what would you want to see in the feature?

Thanks!

**Comment by AngryRhetoric** [comment]
Hi Erik,

Anytime!  And in thinking more about this, yes, it would probably be easiest to have report versions of all the data offered, even if the scope of what's good for "reporting" or "trending" would likely be (far) less.  Other than that, I know it can be very subjective!

Oh yeah, data across servers or in our case into Azure Data Explorer combined with a handful of other metrics we're keeping track of.  Either way, the less data transferred the better!

In specific terms of what I'd like to see in the feature: it would be great to have parameters to enable @Report_Mode and maybe have it be "lite" reporting when @expert_mode = 0 and more verbosity when that's set to 1.  Having it in a permanent table means the data stays around for a while and lets me pick and choose what columns I care about or aggregate it even further before ripping it out to another destination.  
That way the proc developer doesn't have to go too crazy guessing what each person wants.

I hope that helps, let me know if you need any more information.  Also, enjoy the weekend!

**Comment by AngryRhetoric** [comment]
Hi Erik,

I was able to insert the proc results directly into a temp table by adding your "insert into #temptable" statements inside the dynamic SQL :) 
A temporary fix for sure until the reporting mode becomes available, thanks again!

**Comment by erikdarlingdata** [comment]
I haven't run into enough use cases for this, so I'm going to close it out. If you decide you want to work on the issue, I'll re-open it.
