### ISSUE TITLE
Invalid object name '#waits_agg' @debug = 1 mode

### ISSUE THREAD

**Issue by ronaldgithub** [erikdarlingdata/DarlingData#13]
**Version of the script**
SELECT @version = '1.0', @version_date = '20200301';

**What is the current behavior?**
Msg 208, Level 16, State 0, Procedure dbo.sp_HumanEvents, Line 1442 [Batch Start Line 12]
Invalid object name '#waits_agg'.

**If the current behavior is a bug, please provide the steps to reproduce.**
EXEC dbo.sp_HumanEvents @event_type = 'blocking',  @debug = 1;

**What is the expected behavior?**
#waits_agg is not relevant?

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
WIN10 / SQL2019

**Comment by erikdarlingdata** [comment]
Go ahead grab the newest version, that's fixed.


/* erikdarlingdata.com */
/* sql server performance tuning */
________________________________

**Comment by ronaldgithub** [comment]
Thank you, I like the sp!
