### ISSUE TITLE
sp_humanevents recompile_cause on SQL Server 2016

### ISSUE THREAD

**Issue by WinterIssue** [erikdarlingdata/DarlingData#131]
Script Name: sp_humanevents

v2.0

I am running sp_humanevents on SQL 2016 SP2 CU15. The xml generated by the extended event session has the following:

<event name="sql_statement_recompile" package="sqlserver" timestamp="2021-08-18T05:40:39.746Z">
  <data name="recompile_cause">
    <type name="statement_recompile_cause" package="sqlserver" />
    <value>3</value>
    <text>Deferred compile</text>
  </data>

So I can see a statement recompile cause in the XML but sp_humanevents @event_type='recompilations'

does not show me the recompile cause in the output. However, if I turn debug on it shows the recompile cause in the #recompiles_0 table but not in the generated output.

IF @debug = 1 BEGIN SELECT N'#recompiles_0' AS table_name, * FROM #recompiles_0 AS r OPTION(RECOMPILE); END;

            SELECT 
                r.event_time,
                r.event_type,
                r.database_name,
                r.object_name,
                r.statement_text
            FROM #recompiles_0 AS r
            ORDER BY r.event_time
            OPTION(RECOMPILE);

The outputing select does not report the recompile cause. Is there a reason for not showing this or is it an oversight?

Thanks.

**Comment by erikdarlingdata** [comment]
Thanks for letting me know about this! Wow, what a weird oversight. 

This is fixed in both branches now.

**Comment by WinterIssue** [comment]
Thanks Erik!
