### ISSUE TITLE
Creating view dbo.HumanEvents_Parameterization when no compile event exists error

### ISSUE THREAD

**Issue by JiriDolezalSQL** [erikdarlingdata/DarlingData#134]
**Version of the script**
```
SELECT 
    @version = '2.1', 
    @version_date = '20210901';
```

**What is the current behavior?**
Running 
`EXEC sp_HumanEvents @output_database_name = N'some_db', @output_schema_name = N'dbo'`
throws an error

> Msg 156, Level 15, State 1, Procedure HumanEvents_Parameterization, Line 18 [Batch Start Line 0]
> Incorrect syntax near the keyword 'GROUP'.

while @keep_alive = 1 **keeper_HumanEvents_blocking** and **keeper_HumanEvents_query** event is running but **keeper_HumanEvents_compiles** is **not set**.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create @keep_alive = 1 event for type _query_ and _blocking_ like

```
EXEC sp_HumanEvents 
	@event_type = N'query'
	,@query_duration_ms = 500
	,@query_sort_order = N'duration'
	,@keep_alive = 1;

EXEC sp_HumanEvents 
	@event_type = N'blocking'
	,@keep_alive = 1
	,@blocking_duration_ms = 5000;
```
Have no other HumanEvent created.  Then run
`EXEC sp_HumanEvents @output_database_name = N'some_db', @output_schema_name = N'dbo'`
and you'll get the error.

**What is the expected behavior?**
No error :-)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Tested on (SELECT @@VERSION): 

Microsoft SQL Server 2019 (RTM-CU11) (KB5003249) - 15.0.4138.2 (X64)   May 27 2021 17:34:14   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19043: ) 

Microsoft SQL Server 2016 (SP2-CU15-GDR) (KB4583461) - 13.0.5865.1 (X64)   Oct 31 2020 02:43:57   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

**Note:**
I am new to GitHub so accept my apologies if I made any mistake or did not mention or fill up something reporting this.

**Comment by erikdarlingdata** [comment]
Hello @JiriDolezalSQL! Thanks for reporting this. I've finally had a chance to take a look, and I believe I have the appropriate fix in place. Please let me know if it's working correctly for you now.

**Comment by JiriDolezalSQL** [comment]
No more errors in my test. Thank you so much!
