### ISSUE TITLE
sp_HumanEvents

### ISSUE THREAD

**Issue by MsSQLServerDBA** [erikdarlingdata/DarlingData#141]
**Version of the script**
2.1

**What is the current behavior?**

When deploying sp_HumanEvents using DBATools the following error is returned:

WARNING: [09:12:08][Invoke-DbaQuery] [DESKTOP-02TMH0M\SQL2014STD] Failed during execution | Unclosed quotation mark after the characte
r string 'You need to set up the blocked process report in order to use this:
    EXEC sys.sp_configure 'show advanced options', 1;   
'.
Incorrect syntax near 'You need to set up the blocked process report in order to use this:
    EXEC sys.sp_configure 'show advanced options', 1;   
'.

**If the current behavior is a bug, please provide the steps to reproduce.**

Invoke-DbaQuery -SqlInstance $Servers -File "C:\scripts\sp_humanEvents.sql"

**What is the expected behavior?**

The stored procedure should just be deployed to the server(s). It works in SSMS but it doesn't work when it's in a file called by DBATools.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

I'm using SQL Sever 2019 and Windows Server 2019.

**Comment by erikdarlingdata** [comment]
I was reviewing this before writing a blog post about recent changes to the procs, and I noticed that you deleted three of the GO statements, but left in the last one:
![image](https://user-images.githubusercontent.com/2136037/137813477-97fae011-bf25-48cc-a7af-37b5f98fe9f4.png)
Is that intentional, or does it need to be removed? I can do it quickly, or leave it in there, but I wanted to make sure with you first.

Thanks!

**Comment by MsSQLServerDBA** [comment]
Hey Erik!

I just wanted to change as little as possible. It seems to work either with or without the last GO statement so how ever you want to do it is fine with me.

It also seems to work if, instead of removing the GO statements, you add a semicolon after the three GO statements or after all four GO statements, if you prefer.

I think I’ve read about semi colons vs GO statements a few times over the years and … well it seems complicated to me but I recognized it as being the issue when I got the error that I got trying to deploy.

Amy

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MsSQLServerDBA** [comment]
Cool. I'll do that and thanks!
