### ISSUE TITLE
sp_HumanEvents problem with tempdb utilization on @event_type = N'blocking', @keep_alive = 1

### ISSUE THREAD

**Issue by JiriDolezalSQL** [erikdarlingdata/DarlingData#143]
**Version of the script**
SELECT 
    @version = '2.1', 
    @version_date = '20210901';

**What is the current behavior?**
I’ve set up sp_HumanEvents @event_type = N'blocking', @keep_alive = 1 XE session and run EXEC sp_HumanEvents @output_database_name = N'<database>', @output_schema_name = N'dbo' … and left it running.
 
After 12 hours I had to stop this monitoring because of the high utilization of tempdb that almost filled up the dedicated drive unit.
Running sp_WhoIsActive I’ve seen over 14,000,000 in tempdb_allocations column with sp_HumenEvent session. I didn’t mention what was in tempdb_current.
 
I had to act quickly (and in a panic) so unfortunately I didn't take the screenshots – I know this would be very valuable.
I just immediately stopped the collection and the XE session and tempdb stopped growing.

**If the current behavior is a bug, please provide the steps to reproduce.**
I dare not to report this as a bug...maybe it's a wrong usage of sp_HumanEvents - ‚blocking‘ event type is not a good candidate for long-term (days, hours) collection.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2017 (RTM-CU22-GDR) (KB4583457) - 14.0.3370.1 (X64)   Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by erikdarlingdata** [comment]
That's not a bad idea at all. Maybe a silly question: Do you see any of the other session types causing the same issue? It might be worth doing this for others if they do. 

Thanks!

**Comment by JiriDolezalSQL** [comment]
No experiences with other types than = 'blocking' causing this issue. But I am just starting with sp_HumanEvents in my toolbox so it's not much relevant. I tend to stop and start all the HumanEvents XE sessions in the "manager" job (name LIKE N'keeper_HumanEvents%') in my future projects till the resolution.

**Comment by JiriDolezalSQL** [comment]
Can't wait for the blog post you are mentioning. Thanks.
