### ISSUE TITLE
Missing Memory Units in "Figure out who's using a lot of CPU" query

### ISSUE THREAD

**Issue by rvsmann** [erikdarlingdata/DarlingData#144]
**Is your feature request related to a problem? Please describe.**
In the first section of the output, all memory units are in MB as we are querying RESOURCE_SEMAPHORE DMV. In the last section of the output, we are querying sys.dm_exec_requests which means memory units is in pages. I did a completely different analysis by assuming that it is in MB. 

**Describe the solution you'd like**
Make the column name more specific that it is counting pages. 

**Describe alternatives you've considered**
**A possible change in line number 652 to 655, to change the calculation or to the column name.** 

**Are you ready to build the code for the feature?**
Seems to be simple logic, if it makes sense to change it and you allow then I will start working on it.

**Comment by erikdarlingdata** [comment]
I'm assuming this is about `sp_PressureDetector`? If so, makes sense. I think my preference would be to convert the column to calculate pages in MB to standardize it.

If you wanna make that change feel free to fork the repo and make a PR against the dev branch.

Thanks!
