### ISSUE TITLE
Branches used for download and installation by dbatools

### ISSUE THREAD

**Issue by andreasjordan** [erikdarlingdata/DarlingData#150]
Hi Erik!

As there is a branch called "main" and another called "master": Which one should we download using https://docs.dbatools.io/Save-DbaCommunitySoftware and install using https://docs.dbatools.io/Install-DbaDarlingData?
Currently we use "master" as default and also allow "dev".
What should we allow?
What should be the default?

Greetings
Andreas

**Comment by erikdarlingdata** [comment]
@andreasjordan I'm trying to move away from master, please use main.

**Comment by andreasjordan** [comment]
Thanks, will open a pull request for that soon.
