### ISSUE TITLE
Add options to sort by Total CPU, Total Logical reads

### ISSUE THREAD

**Issue by stevepmo** [erikdarlingdata/DarlingData#156]
**Is your feature request related to a problem? Please describe.**
Today I wanted to Select the top 25 queries from QueryStore sorted by Total CPU desc, I tried CPU but that gave me the average CPU so didn't account for the number of executions.

**Are you ready to build the code for the feature?**
Possibly - I mean I like dynamic SQL as much as the next guy but this is boss level stuff

**Comment by erikdarlingdata** [comment]
I tend to avoid these sort orders, because they're not what I want to go after for query tuning. Thanks for the suggestion, though.
