### ISSUE TITLE
sp_humanevents custom schema error.

### ISSUE THREAD

**Issue by cankaya07** [erikdarlingdata/DarlingData#157]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

**What is the current behavior?**
its getting or looling dbo schema when try to export result of query. I want to export data specific schema insted of dbo.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by erikdarlingdata** [comment]
This should be fixed now in the [dev branch](https://github.com/erikdarlingdata/DarlingData/tree/dev).
