### ISSUE TITLE
`sp_HumanEvents` - `showplan_xml` Greater Than 128 Nodes

### ISSUE THREAD

**Issue by mattcargile** [erikdarlingdata/DarlingData#158]
**Version of the script**
`2.92`
`20211101`

**What is the current behavior?**
Failure to convert query plan xml if greater than 128 nodes or maybe the statement is removed from the output?. I only received this error one time and I couldn't recreate it. I was mainly wondering if this was a thought in the handling. I looked at the below line and it appears there is an "implicit" cast to `xml`?

https://github.com/erikdarlingdata/DarlingData/blob/c53b533184424156eba17ec5bc4861b908afd330/sp_HumanEvents/sp_HumanEvents.sql#L1864

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a "complex" query and have its plan be complicated with lots of nodes. _I think._

**What is the expected behavior?**
Maybe report `NULL` or ideally report `nvarchar` of the xml or maybe `nvarchar` of a query to get the text in `xml`. I see [this issue](https://github.com/erikdarlingdata/DarlingData/issues/67) after I made this. I see you mention `TRY_CONVERT` within it. Would it be reasonable to add `TRY_CAST`, that is supported in 2012 compat now I guess theoretically this would break folks with earlier compats on SQL Server 2012. Hmm...
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I was received the issue on SQL Server 2014.

**Comment by erikdarlingdata** [comment]
There's really not an easy way to do this, and it has to do with the way query plan XML gets stored from the event session. At some point, it has to end up as XML. 

Trying to pull it out by replacing the line you mentioned with this:
```
c.value('(data[@name="showplan_xml"]/value/*)[1]', 'nvarchar(MAX)') AS showplan_xml,
```
Give me empty strings. If you can figure out a way around that, let me know and I'll reopen the issue. For now, I'm gonna close this out.

**Comment by mattcargile** [comment]
Gotcha. What about the way Adam is doing it here where he wraps the `xml` as "text" within `xml`?

https://github.com/amachanic/sp_whoisactive/blob/6ac5631445ee611abab89eb1b44570d625010caa/sp_WhoIsActive.sql#L4407-L4413

**Comment by erikdarlingdata** [comment]
Like I said, if you want to give it a shot, you're more than welcome to.
