### ISSUE TITLE
exec sp_HumanEvents @event_type = 'blocking' Getting Blocked

### ISSUE THREAD

**Issue by imajaydwivedi** [erikdarlingdata/DarlingData#160]
**Version of the script**
`@version = '2.92', @version_date = '20211101';`

**What is the current behavior?**
`exec sp_HumanEvents @event_type = 'blocking'` is itself blocked by another user session

**Below were the output in messages tab** -
> Setting up some variables
> Checking for some event existence
> Nixing NULLs
> Sanity checking event types
> Checking query duration filter
> Checking wait duration filter
> Checking block duration filter
> Checking query sort order
> Parsing any supplied waits
> Avoiding disappointment
> Are we trying to filter for a blocking session?
> Validating if the Blocked Process Report is on, if the session is for blocking
> If there's a database filter, is the name valid?
> If there's a session id filter, is it valid?
> No dividing by zero
> Wait For It! Wait For it!
> Make sure the session doesn't exist already
> Does the output database exist?
> Does the output schema exist?
> Is output database OR schema filled in?
> Is custom name something stupid?
> Someone is going to try it.
> Do we skip to the GOTO and log tables?
> Do we skip to the GOTO and cleanup?
> Setting up individual filters
> Combining session filters
> Setting up the event session

**Below were the blocking details I captured using `sp_WhoIsActive`** -
![image](https://user-images.githubusercontent.com/101084432/169342064-10d2957b-99c2-40a0-83fb-3deff8f5d4e2.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
`exec sp_HumanEvents @event_type = 'blocking'`

**What is the expected behavior?**
I don't expect code to find blocking details itself getting blocked :)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
[13.0.5850.14](https://support.microsoft.com/en-us/help/4577775)

**Comment by erikdarlingdata** [comment]
I don’t create a temp table called #TRADE which means you’ve got tempdb contention issues that I can’t fix.
