### ISSUE TITLE
sp_WhoIsActive Logging - Implicit conversion error

### ISSUE THREAD

**Issue by DrummerDBA** [erikdarlingdata/DarlingData#181]
**Version of the script**
sp_WhoIsActive Logging.sql - Latest commit [0a81c05](https://github.com/erikdarlingdata/DarlingData/commit/0a81c053bcacc68fb91e8c15614b399b25964280) 26 days ago

**What is the current behavior?**
I found I was getting the following error when running your “sp_WhoIsActive Logging” script:
Msg 257, Level 16, State 3, Procedure sp_add_jobschedule, Line 32
Implicit conversion from data type datetime to int is not allowed. Use the CONVERT function to run this query.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run the “sp_WhoIsActive Logging” script on SQL Server 2014 with English British language settings.

**Fix**
I fixed this issue by changing the @active_start_date declare to:
	@active_start_date int = Convert( int, Convert( varchar(8), GETDATE(), 112 ) );

**Comment by erikdarlingdata** [comment]
Yeah, thanks. I had just fixed that in my Ola script yesterday: https://github.com/erikdarlingdata/DarlingData/commit/cb263e65f4fe74850d68baeb029999ca090ac41a

Forgot about this one. I'll take care of it now.
