### ISSUE TITLE
Logging result to the table from HumanEvents SP

### ISSUE THREAD

**Issue by UriDimant** [erikdarlingdata/DarlingData#184]
Hi Erik, I would like to thank you for the great stored procedure sp_HumanEvents which has been helping me a lot on my day by day job.
Permit me to ask you one question, how I'd like to log into the table all queries that running more than 10 sec, I have seen your video explanation about it, so just tell me if I am on the right way.
EXEC sp_HumanEvents
@event_type = 'query',
@query_duration_ms = 10000,
@keep_alive=1

EXEC sp_HumanEvents
@output_database_name = N'DBA',
@output_schema_name = N'dbo'

select top 100 * from [DBA].[dbo].[keeper_HumanEvents_query]

Is it all? Just query the table ? BTW I want the EE to be run every day.... I tried to stress and ran some query on one of the db
SELECT * FROM SYS.OBJECTS CROSS JOIN SYS.OBJECTS AS D CROSS JOIN (SELECT TOP 100 * FROM SYS.OBJECTS) AS C
It completed in 30 sec but nothing get logged into the table.. I am sure I am missing something....

Thank you.

**Comment by erikdarlingdata** [comment]
I think what you're missing is that you need something to collect the data from the event session and put it into the tables. See the [Agent Job example](https://github.com/erikdarlingdata/DarlingData/blob/main/sp_HumanEvents/sp_Human%20Events%20Agent%20Job%20Example.sql).

**Comment by HannahVernon** [comment]
The example job is set to start every 10 seconds to enable continuous capture of events data.  Check the job history to see how long it runs each time.

**Comment by erikdarlingdata** [comment]
Apart from the job running in a loop, there's a loop in the procedure to continuously monitor the sessions. It's not running forever, it's internally looping.

**Comment by UriDimant** [comment]
I canceled the job after 15 min running on  the calm server
