### ISSUE TITLE
ran tempdb out of space

### ISSUE THREAD

**Issue by genetsmartx** [erikdarlingdata/DarlingData#185]
**Version of the script**
    @version = '3.33', 
    @version_date = '20220701';

**What is the current behavior?**
    @version = '3.33', 
    @version_date = '20220701';
**If the current behavior is a bug, please provide the steps to reproduce.**
I started watching recompiles, e.g. EXEC sp_HumanEvents @event_type = N'recompiles', @keep_alive = 1;

I started running in a job ever 10 sec: EXEC sp_HumanEvents @output_database_name = N'HCVAdmin', @output_schema_name = N'dbo';
I ran tempdb out of space.  It created too many temp objects.

**What is the expected behavior?**

it should release temp objects 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2014
Microsoft SQL Server 2014 (SP3-**GDR**) (KB5014165) - 12.0.6169.19 (X64)   Apr 21 2022 18:01:27   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by erikdarlingdata** [comment]
i've got a fix for this coming shortly. thanks for the heads up!
