### ISSUE TITLE
sp_PressureDetector for Azure SQL DB

### ISSUE THREAD

**Issue by samplesty** [erikdarlingdata/DarlingData#187]
sp_PressureDetector currently fails on Azure SQL DB because of the following reference:

```
SELECT 
    CEILING
    (
        dosm.total_physical_memory_kb / 1024.
    )
FROM sys.dm_os_sys_memory AS dosm
```

Would it be possible to aggregate across memory nodes to calculate this, which is available in Azure SQL DB? Something like seems to work for me.

```
SELECT 
    SUM
    (
        domn.target_kb / 1024.
    )
FROM sys.dm_os_memory_nodes AS domn
```

I'm happy to submit a PR if this sounds reasonable.

**Comment by erikdarlingdata** [comment]
Sure, go for it.

**Comment by samplesty** [comment]
Thanks for your consideration! I'm getting a lot out of your training and excited to learn more about your tools!

**Comment by samplesty** [comment]
Crap! Here's the PR link: https://github.com/erikdarlingdata/DarlingData/pull/188
