### ISSUE TITLE
sp_HumanEvents @object_name is too strict and the @query_duration_ms override is hard to see

### ISSUE THREAD

**Issue by codykonior** [erikdarlingdata/DarlingData#207]
**Is your feature request related to a problem? Please describe.**

These are some new user experience problems I had.

1) When running sp_HumanEvents for @event_type = 'query', @object_name = 'xxx' the sanitizer is too broad, excluding any stored procedure names that have words like SELECT, INSERT, UPDATE etc in them.

  If you think about it, those are really common procedure names. SelectCustomer, UpdateAddress, etc. It makes the command kind of unusable for tracking procedure specific executions. Below is the problematic code.

```
SELECT     
            1/0    
        FROM #papers_please AS pp    
        WHERE pp.ahem LIKE N'%SELECT%'    
        OR    pp.ahem LIKE N'%INSERT%'    
        OR    pp.ahem LIKE N'%UPDATE%'    
        OR    pp.ahem LIKE N'%DELETE%'    
        OR    pp.ahem LIKE N'%DROP%'    
        OR    pp.ahem LIKE N'%EXEC%'    
        OR    pp.ahem LIKE N'%BACKUP%'    
        OR    pp.ahem LIKE N'%RESTORE%'    
        OR    pp.ahem LIKE N'%ALTER%'    
        OR    pp.ahem LIKE N'%CREATE%'    
        OR    pp.ahem LIKE N'%SHUTDOWN%'    
        OR    pp.ahem LIKE N'%DBCC%'    
        OR    pp.ahem LIKE N'%CONFIGURE%'    
        OR    pp.ahem LIKE N'%XP[_]CMDSHELL%'    
    )    
    BEGIN    
        RAISERROR(N'Say... you wouldn''t happen to be trying some funny business, would you?', 11, 1) WITH NOWAIT;    
        RETURN;    
    END;    
```

2) While trying to diagnose this, I then I also fell afoul of the @query_duration_ms block which forces any input of 0 to 500 by default, and outputs in the messages window a suggestion to use @gimme_danger = 1.

  I was trying it out in a lower environment to see the impact, before going to a higher environment, and wondering why my test cast wasn't triggering. I had no idea to look at the messages window, which is, you know, quite a few lines of text, and it's kind of buried in there unexpectedly.

  Because the test case failed, I didn't proceed further with it and switched to another tool. Like, I wonder if other people do that and think it just doesn't work.

  I think it would be a much better user experience to throw an error if you pass 0 unless @gimme_danger = 1. That way it's clear what is happening. When it gets quietly changed to 500 it's very hard to know that's what happens, unless you dig into it.

**Describe the solution you'd like**
I would be okay with @gimme_danger = 1 skipping this part of the sanitizer check, or just the object_name part of that check.

And optionally throwing an error on @query_duration_ms of 0 unless @gimme_danger = 1. I think this is good for users, and anyone trying out the command in the early stages and wondering why it's not working.

What do you think?

**Are you ready to build the code for the feature?**
Sure.

**Comment by erikdarlingdata** [comment]
Alright, so just to summarize a little:
* Ditch the SELECT/INSERT/UPDATE/DELETE checks from the sanitizer
* Throw an error when the query duration is under 500ms rather than just printing out that it's being reverted

If that sounds about right, I'm totally cool with the changes. If you're into it, go for it. Otherwise I can knock those out tomorrow.

Thanks!

**Comment by erikdarlingdata** [comment]
@codykonior wanted to follow up on this just in case you didn't get a ping.

**Comment by codykonior** [comment]
Yes I will get on this, thanks.

**Comment by codykonior** [comment]
Thanks for that! I've been a bit busy 😓

**Comment by erikdarlingdata** [comment]
No worries! I was in there poking around at some other stuff and figured I might as well.
