### ISSUE TITLE
Azure Hyperscale sys.query_store_runtime_stats | page_server_io fields

### ISSUE THREAD

**Issue by mattnis** [erikdarlingdata/DarlingData#211]
Thank you for this project, I find it very useful.
The results are just missing a few fields from sys.query_store_runtime_stats that relate to hyperscale databases.

https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-query-store-runtime-stats-transact-sql?view=sql-server-ver16

Please see the fields  with description containing:
**Applies to: Azure SQL Database Hyperscale**

avg_page_server_io_reads
..
..
stdev_page_server_io_reads

**Comment by erikdarlingdata** [comment]
@mattnis I'm not interested in supporting that at all. If you'd like to add the code, you're welcome to do so and submit a pull request.

**Comment by mattnis** [comment]
Not interested in supporting the project or just not supporting
Hyperscale?   These page_server_io fields are also relevant for performance
tuning.

-Matt-

**Comment by erikdarlingdata** [comment]
@mattnis not interested in supporting hyperscale. I don’t use it or have access to it for testing, and I don’t have any clients who use it. If it’s important to you, feel free to submit a pull request.

**Comment by erikdarlingdata** [comment]
@mattnis I haven't heard back from you on completing this in a couple months now, so I'm going to close it out.
