### ISSUE TITLE
Default retention period for tables created by sp_WhoIsActive Logging

### ISSUE THREAD

**Issue by deffinity** [erikdarlingdata/DarlingData#216]
**Is your feature request related to a problem? Please describe.**
Sooo... [sp_WhoIsActive Logging](https://github.com/erikdarlingdata/DarlingData/tree/main/sp_WhoIsActive%20Logging) is great and all but it lacks default retention period for tables it creates. I can't set it and forget it because alerts about 'master' DB size growing fast (quite) won't let me forget.

**Describe the solution you'd like**
I'd like whiskey as a solute and apple juice as a solvent, but - things can be done with some default parameter (like say retention_days) in [02 sp_WhoIsActiveLogging Main.sql](https://github.com/erikdarlingdata/DarlingData/blob/main/sp_WhoIsActive%20Logging/02%20sp_WhoIsActiveLogging%20Main.sql) and then call a dynamic sql that drop tables with creation date earlier than current date minus the retention_days. Tables should be dropped before the views creation for obvious reason.

**Describe alternatives you've considered**
I've considered quitting my job but that's not an option right now

**Are you ready to build the code for the feature?**
Yes? No? Maybe? Sure? Your formatting is quite complex and I'm bit scary. Also maybe you'll consider that's not an option. The tables cursor can be taken from [01 sp_WhoIsActive Logging Views.sql](https://github.com/erikdarlingdata/DarlingData/blob/main/sp_WhoIsActive%20Logging/01%20sp_WhoIsActive%20Logging%20Views.sql), adjuster for drop and where'd by creation date.

**Comment by erikdarlingdata** [comment]
If you're going to make me read all this at 8am, the least you can do is contribute what you think is a reasonable default for the retention period 😉

**Comment by erikdarlingdata** [comment]
I'm heading into a call, but I made a first pass attempt at implementing this. Check the versions in the dev branch and give them a test run.

**Comment by erikdarlingdata** [comment]
Cool -- did you have to make any changes, or did you hit any errors while you were implementing it? Or did it work out of the box?

**Comment by deffinity** [comment]
None errors, nor changes. I just dropped every old sp and job, then run the scripts in order - prune sp, view sp, main sp, job. And then it worked smoothly.
