### ISSUE TITLE
Divide by zero

### ISSUE THREAD

**Issue by deffinity** [erikdarlingdata/DarlingData#229]
This line here can be 0 if there are some files no writes, I caught "Divide by zero error encountered" with what_to_check undefined.

https://github.com/erikdarlingdata/DarlingData/blob/a03e30ce6454a8256d6b5d241fc7ca56d1859a47/sp_PressureDetector/sp_PressureDetector.sql#L584

**Comment by erikdarlingdata** [comment]
Oh I see yeah, the where clause for that query is incorrect. I'll fix it shortly.
