### ISSUE TITLE
Add the ability to return queries only from procedures/functions;  Display summary resource usage data by procedure/function

### ISSUE THREAD

**Issue by MinnRick** [erikdarlingdata/DarlingData#230]
Similar to the existing capability in the sp_BlitzCache procedure offered by the @QueryFilter parameter, I am requesting the addition of a filtering capability, presumably implemented through a new parameter, to allow the caller to specify that only queries from within stored procedures and functions be returned in the result set.  It is often helpful to differentiate queries by their source type and such a capability would be immediately useful for users attempting to diagnose which stored procedures or functions are causing the most performance mischief.

As a Part II to this request, it would be even more helpful if aggregate performance and resource utilization data could also be displayed, grouped by procedure/function for all of the queries within the source.  I would envision this as an added result set to the procedure's output, perhaps displayed only when the '@ReturnProcedureQueriesOnly' parameter is used in an execution.  By-procedure summary data would be a perfect compliment to the procedure-only queries returned in the first part of the request.

**Comment by erikdarlingdata** [comment]
@MinnRick I've got the filtering part in, but not the aggregate information. Can you give me an example table structure for what you would like to see?
