### ISSUE TITLE
sp_QuickieStore - Adjust for UTC Timestamps Used in Query Store

### ISSUE THREAD

**Issue by MinnRick** [erikdarlingdata/DarlingData#237]
Good Evening Erik.  Following up on an email exchange we had a few weeks ago..  From what I can tell, Query Store stores the timestamps for query executions and their related data using UTC.  This is a bit cumbersome to adjust for when using the @start_date and @end_date parameters with times in sp_QuickieStore.  In your email reply you suggested the following to help get the times right:
SELECT
    sdt = SYSDATETIME(),
    sudt = SYSUTCDATETIME(),
    dd = DATEDIFF(HOUR, SYSDATETIME(), SYSUTCDATETIME());

My request is for this capability to be built into the sproc so that the parameters can simply take and process results using the local time(s) (for the server) when the query/queries in question ran, without having to deal with DATEDIFF'ing every execution when timestamps are getting used.  Thanks.

And also, THANK YOU for your excellent work on behalf of the SQL community!

**Comment by erikdarlingdata** [comment]
@MinnRick  Please give the version of QS in [dev](https://github.com/erikdarlingdata/DarlingData/tree/dev/sp_QuickieStore)a shot. If you encounter any bugs or unexpected behavior, please respond with as much detail as possible, along with anything reproducible.

**Comment by erikdarlingdata** [comment]
@MinnRick okay, this is too much of a pain in the butt to get working Gonna bail on it, but if you feel like working on it, feel free.

**Comment by erikdarlingdata** [comment]
@MinnRick  Oops, didn't mean to close that out. I think I got it working now, if you check the dev branch. The deal is you have to choose a valid time zone from `sys.time_zone_info` and use that, since I can't detect it easily without reading the registry.
