### ISSUE TITLE
Querying WhoIsActive-table returns an error in SSMS

### ISSUE THREAD

**Issue by ghauan** [erikdarlingdata/DarlingData#243]
**Version of the script**
I could not find a version number in your logging-procedures (I downloaded them a couple of days ago), but my version of sp_whoisactive is :
v12.00 (2021-11-10)

**What is the current behavior?**
I was just starting playing around with your advanced logging of sp_whoisactive. I created your procedures in a dba-database, but sp_whoisactive is in master. After the agent job had run for a couple of minutes, I tried querying the view. It went OK for a while, but then suddenly I got the following error:
An error occurred while executing batch. Error message is: Name cannot begin with the '=' character, hexadecimal value 0x3D. Line 1549, position 31.
One of the rows was causing the error. I tracked it down to being the sql_text-column where the problem was. If I commented that out, I could get the data. Turns out I also had some logging from sp_blitzfirst running, and it is something from that query-text that is causing the problem. I am not sure what.

**If the current behavior is a bug, please provide the steps to reproduce.**
While your solution was saving data to the log-tables, I had the following query running in another agent-job:
exec sp_blitzfirst @ExpertMode=1,
	@OutputDatabaseName =  'DBAtoolsHVI',
	@OutputSchemaName = 'dbo',
	@OutputTableName = 'BlitzFirst',
	@OutputTableNameFileStats = 'BlitzFirst_FileStats',
	@OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
	@OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
	@OutputTableNameBlitzCache = 'BlitzCache',
	@OutputTableNameBlitzWho = 'BlitzWho'

**What is the expected behavior?**
I would like to be able to query from the log tables without having to comment out the sql_text column. 
When the problem first occur, it would be easier if the tables had an IDENTITY column or something that identified each row, so that the problem row could be deleted or updated.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2019 (RTM-CU20) (KB5024276) - 15.0.4312.2 (X64)   Apr  1 2023 12:10:46   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by erikdarlingdata** [comment]
@ghauan this is a bug in Who Is Active, not in my logging script. Please file a report in that repo: https://github.com/amachanic/sp_whoisactive
