### ISSUE TITLE
Sorting sp_QuickieStore output by total CPU instead of average CPU

### ISSUE THREAD

**Issue by m60freeman** [erikdarlingdata/DarlingData#247]
**Which script is your question about?**

Script Name: sp_QuickieStore

**Script version**

>All scripts have a version and version date. Make sure you're on a recent version.

I downloaded it a few minutes ago, but there is no version or version date.

I would like to have results sorted by total cpu but that isn't an option. I want to use it for identifying the statements that are overall most responsible for the cpu usage on Azure SQL Databases. Is there a way you would recommend involving query store data to achieve that or should I submit a feature request?

**Comment by erikdarlingdata** [comment]
Hi Mark,

All scripts have versions and dates. For QuickieStore, it’s currently on line 118

```
SELECT
    @version = '3.70',
    @version_date = '20230701';
```

For your feature request, it’s not something I’d ever implement. Total CPU is often a total waste of time from a tuning perspective. You’re almost always better off sorting by executions, or setting a minimum number of executions with average CPU. 

Thanks!
