### ISSUE TITLE
Msg 105 Unclosed quotation mark after the character string '(data[@name="is_recompi'.

### ISSUE THREAD

**Issue by gflpcantor31** [erikdarlingdata/DarlingData#273]
First of all, I'd like to thank you for your work, which I imagine is intense and requires a lot of effort. Many thanks. Your work is of public utility 

**Version of the script**
dbo.sp_HumanEvents
version : '5.0',    
version_date : '20230801';   

**What is the current behavior?**
I regularly get the following error: 
_Msg 105, Level 15, State 1, Line 67
Unclosed quotation mark after the character string '(data[@name="is_recompi'._

According to my investigations, the problem lies in the following SQL statement : 
The problem stems from the fact that the content of the @table_sql variable is systematically truncated at 4000 characters, which explains the origin of the error, since, in reality, the query text exceeds 4000 characters.
```
INSERT INTO [My_Database].[dbo].keeper_HumanEvents_compiles WITH(TABLOCK) 
( server_name, event_time,  event_type,  
  database_name, object_name, statement_text , compile_cpu_ms, compile
..... 
.....
.....
    oa.c.value('xs:hexBinary((data[@name="statement_sql_hash"]/value/text())[1])', 'varbinary(64)') AS statement_sql_hash   
FROM #human_events_xml_internal AS xet   
OUTER APPLY xet.human_events_xml.nodes('//event') AS oa(c)   
WHERE oa.c.exist('@name[.= "query_parameterization_data"]') = 1   
AND   oa.c.exist('(data[@name="is_recompi
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
EXEC sp_HumanEvents
    @event_type = N'compiles',
    @keep_alive = 1;

EXEC sp_HumanEvents
    @event_type = N'recompiles',
    @keep_alive = 1;

EXEC sp_HumanEvents
    @event_type = N'query',
    @keep_alive = 1; 

EXEC sp_HumanEvents
    @event_type = N'waits',
    @keep_alive = 1; 

EXEC sp_HumanEvents
    @event_type = N'blocking',
    @keep_alive = 1; 

EXEC sp_HumanEvents
    @output_database_name = N'My_Database',
    @output_schema_name = N'dbo'; 
```

**What is the expected behavior?**
Make sure that when the query text is too long, exceeding 4000 characters, it's not truncated and therefore doesn't generate an error. 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2019 (RTM-CU18-GDR) (KB5021124) - 15.0.4280.7 (X64) 
Jan 23 2023 12:37:13 
Copyright (C) 2019 Microsoft Corporation
Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: ) (Hypervisor)

**Comment by erikdarlingdata** [comment]
@gflpcantor31 thanks for reporting this. It didn't come up in any of my testing. 

It's sort of an unfortunate state of things with dynamic SQL where at different times in different places string concatenation sometimes implicitly converts to lower byte lengths, causing these truncation errors. There's no great workaround for it other than to add a convert to nvarchar max around every string fragment, which is pretty tedious.

In the meantime, if you find which concatenation point in the dynamic SQL causes this, please let me know.

**Comment by erikdarlingdata** [comment]
@gflpcantor31 can you try the version in the dev branch and let me know if that resolves the error for you?

**Comment by erikdarlingdata** [comment]
@gflpcantor31 If you open a proper pull request with these changes, I'm happy to take a look. It's a bit much to ask me to scroll through 3000 lines looking for your changes and then copying them over into my local file. Thanks!
