### ISSUE TITLE
sp_QuickieStore unexpected default @end_date

### ISSUE THREAD

**Issue by renederoos** [erikdarlingdata/DarlingData#282]
**Version of the script**
version: 4.1
version date: 2023-09-01

**What is the current behavior?**
Executing sp_quickiestore without setting @end_date defaults to an end date of 00:01 AM today.
This is also confirmed by the debug info.

![sp_quickiestore_no-enddate_parameters](https://github.com/erikdarlingdata/DarlingData/assets/90823353/0c07fafc-ff60-47bc-91b0-d740bbc5bbbe)

According to the help @end_date should be NULL by default.

![sp_quickiestore_help](https://github.com/erikdarlingdata/DarlingData/assets/90823353/4dec708a-6cf0-4d0f-a516-70a7380fed67)

**If the current behavior is a bug, please provide the steps to reproduce.**
`exec sp_quickiestore;`
Executing sp_quickiestore with @end_date set to tomorrow will give the correct results.

![sp_quickiestore_enddate_difference](https://github.com/erikdarlingdata/DarlingData/assets/90823353/48e27bd8-f523-483e-b6e1-2f367791fe8e)

**What is the expected behavior?**
Executing sp_quickiestore without setting @end_date should also include todays runtime stats (if available).

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Previous version 4.0 has the same issue.
I guess this behavior has been introduced with one of the recent UTC changes.

The version of my current test system is:
Microsoft SQL Server 2019 (RTM-CU21) (KB5025808) - 15.0.4316.3 (X64) Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)
Both, my workstation and the database server, have their timezone set to CEST (UTC +02:00).

**Comment by erikdarlingdata** [comment]
Ooh good catch. Yeah, the old behavior was to add a full day to today's date when that parameter is null. I'll get a fix in today. Thanks!

**Comment by renederoos** [comment]
Thanks for fixing and many thanks for all the cool stuff you share with us (including the YT vids)!

**Comment by erikdarlingdata** [comment]
Yeah, happy to share. Give the dev branch version a shot and let me know if that works for you as well.

**Comment by renederoos** [comment]
Working as designed.

Thanks again!
