### ISSUE TITLE
Given @days_back is always negative then this would always return @days_back 

### ISSUE THREAD

**Issue by shaunscott12** [erikdarlingdata/DarlingData#293]
**Which script is your question about?**

Script Name:
https://github.com/erikdarlingdata/DarlingData/blob/main/sp_LogHunter/sp_LogHunter.sql
**Script version**

All scripts have a version and version date. Make sure you're on a recent version.

**Is your question about how they work, or the results?**
Not a real big deal, but I think this should be 
Questions about *how the scripts work* can be answered here. 

If you have questions about the results, performance tuning, or SQL Server in general, you'll wanna hit a Q&A site:

 * [Top Answers](https://topanswers.xyz/databases)
 * [Stack Exchange](https://dba.stackexchange.com/)

**Okay, what's your question?**
Wonder if  line 331 should be comapring @days_back to -90 rather than 90
 `    N'"' + CONVERT(nvarchar(10), DATEADD(DAY, CASE WHEN @days_back < -90 THEN -90 ELSE @days_back END, SYSDATETIME()), 112) + N'"'`
Enter your query and press F5.

**Comment by erikdarlingdata** [comment]
Heh, well, you're right that it's wrong, and I really appreciate you bringing it to my attention, but it should really be this:

```
DECLARE
    @day_backs int = -120

SELECT
    CASE
        WHEN @day_backs > -90
        THEN -90
        ELSE @day_backs
    END
```
Because -120 is a larger negative number than -90.

Or something.
