### ISSUE TITLE
get_numbers fails on NULL strings

### ISSUE THREAD

**Issue by cdawson1971** [erikdarlingdata/DarlingData#32]
The functions work but they don't handle NULL strings.

```
CREATE TABLE #dummy (col1 VARCHAR(50))

INSERT INTO #dummy VALUES (NULL)
INSERT INTO #dummy VALUES ('ABC123')

SELECT  d.col1, gn.*
FROM #dummy d
    CROSS APPLY dbo.get_numbers(d.col1) AS gn

Msg 1014, Level 15, State 1, Line 25
A TOP or FETCH clause contains an invalid value.

-- works if you denullify on the way in
SELECT  d.col1, gn.*
FROM #dummy d
    CROSS APPLY dbo.get_numbers(ISNULL(d.col1, '')) AS gn

col1   numbers_only
------ ------------
NULL   NULL
ABC123 123
```
If you update the function code to handle the NULLs you don't have to worry about it as the caller. Not sure the impact on performance but something like:

```
WITH x
  AS ( SELECT TOP (LEN(ISNULL(@string, '')))

```
Then call without errors, without checking for NULL:

```
SELECT  d.col1, gn.*
FROM #dummy d
    CROSS APPLY dbo.get_numbers(d.col1) AS gn

col1   numbers_only
------ ------------
NULL   NULL
ABC123 123

```

**Comment by erikdarlingdata** [comment]
Awesome! I'll get this fixed. I'm gonna branch to have two versions: one set that work off a numbers table and one that work of an internal CTE. I've used your suggestion for other things in the past, and I don't think there's a perf hit checking for nulls there.
