### ISSUE TITLE
Workdays flag causes error when @get_all_databases = 1

### ISSUE THREAD

**Issue by tominyorks** [erikdarlingdata/DarlingData#340]
**Version of the script**
4.13 (date 01/01/2024)

**What is the current behavior?**
When `@workdays` = 1 and `@get_all_databases` = 1, an error is thrown when there's more than one database to assess and the second database starts being processed. What's also a little confusing about the error is that the message printed includes the last dynamic SQL that ran and assumes that's where the error occurred - but the error doesn't actually occur with any of the dynamic SQL.

```
Msg 50000, Level 11, State 1, Procedure dbo.sp_QuickieStore, Line 7482 [Batch Start Line 0]
error while checking query store waits are enabled with @expert mode = 0 and format_output = 1
offending query:

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT
    @query_store_waits_enabled =
        CASE
            WHEN EXISTS
                 (
                     SELECT
                         1/0
                     FROM [MyFantasticDatabase].sys.database_query_store_options AS dqso
                     WHERE dqso.wait_stats_capture_mode = 1
                 )
            THEN 1
            ELSE 0
        END
OPTION(RECOMPILE);

Msg 512, Level 16, State 1, Procedure dbo.sp_QuickieStore, Line 2050 [Batch Start Line 0]
Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```sql
EXEC dbo.sp_QuickieStore
	@get_all_databases = 1,
	@workdays = 1,
	@work_start = '8am',
	@work_end = '6pm'
```

**What is the expected behavior?**
I can run against all databases, filter it by work days only, and get results instead of an error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I've only tested in SQL 2019 CU22, it didn't seem necessary to test in other versions given the nature of the problem. This has only become an issue since the introduction of the `workdays` parameter

**Comment by tominyorks** [comment]
After much confusion believing that dynamic SQL was the issue, I found the actual issue is with the population of the `#am_pm` table which occurs inside the main `database_cursor`. This means once the first database has been processed, duplicate rows are entered in this temp table on the second time around the cursor, and we then get the `Subquery returned more than 1 value` error.

**Comment by tominyorks** [comment]
Yowsers....that was quick! Thanks @erikdarlingdata

**Comment by erikdarlingdata** [comment]
@tominyorks hahaha, yeah, well, you did all the hard work. I just forgot to add a truncate statement to `#am_pm` like I had to for some other tables. I suppose it would have been more obvious if I had a unique constraint or something on it like I do the others.
