### ISSUE TITLE
Error in the help text of sp_HumanEventsBlockViewer

### ISSUE THREAD

**Issue by zikato** [erikdarlingdata/DarlingData#355]
[Line 94 ](https://github.com/erikdarlingdata/DarlingData/blob/5d540b39f8bfe403961d2119c7f514a65e289b80/sp_HumanEvents/sp_HumanEventsBlockViewer.sql#L94)   says

> SELECT  'EXEC sp_HumanEvents @event_type = N''blocking'', @keep_alive = 1;' UNION ALL

But it should reference  `sp_HumanEventsBlockViewer`
Also, there is no parameter `@event_type`.

Looks like a copy-paste error

**Comment by erikdarlingdata** [comment]
@zikato no, that's showing how to set up the blocked process report event with sp_HumanEvents.

> hi, i'm sp_HumanEventsBlockViewer!
> you can use me in conjunction with sp_HumanEvents to quickly parse the sqlserver.blocked_process_report event
> EXEC sp_HumanEvents @event_type = N'blocking', @keep_alive = 1;
> it will also work with another extended event session to capture blocking

But I do see why that looks confusing, so I'm going to add a line with an example execution of sp_HumanEventsBlockViewer

**Comment by zikato** [comment]
Ahh, that makes sense. But yes, that's exactly what confused me.

**Comment by erikdarlingdata** [comment]
Closed via #356
