### ISSUE TITLE
sp_QuickieStore - New parameter that allow to only show queries with Query Hints (2022+)

### ISSUE THREAD

**Issue by ClaudioESSilva** [erikdarlingdata/DarlingData#364]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Support a new parameter (example: `@only_query_with_hints`) that only retrieves queries with any Query Hint applied.

Within `sp_QuickieStore` when this parameter is used `@only_query_with_hints = 1` it will filter by queries with entries on the `sys.query_store_query_hints`.
The suggested output when that parameter is 1 is the main one plus the content of the `sys.query_store_query_hints`.

![image](https://github.com/erikdarlingdata/DarlingData/assets/19521315/78d45241-a521-4df3-b1fa-0a980f020145)

When  `@only_query_with_hints = 0` (default) we get the regular output:
![image](https://github.com/erikdarlingdata/DarlingData/assets/19521315/81d53728-b708-46b2-bcd0-95c58639db0b)

With `@expert_mode = 1`:
![image](https://github.com/erikdarlingdata/DarlingData/assets/19521315/94243496-c307-433b-ba45-3e16e66bad7d)

With both `@expert_mode = 1` and `@only_query_with_hints = 1`:
![image](https://github.com/erikdarlingdata/DarlingData/assets/19521315/d545497d-e63b-491a-8ec5-a7138171a67c)

**Describe alternatives you've considered**
Having a custom script to grab the same thing. But I use `sp_QuickieStore` a lot so, having this built-in would be a win-win

**Are you ready to build the code for the feature?**
Yes. I will submit a PR with the code changes for review.

**Comment by erikdarlingdata** [comment]
Closed via #366
