### ISSUE TITLE
HumanEvents_Blocking fails in query

### ISSUE THREAD

**Issue by tpbrownec** [erikdarlingdata/DarlingData#38]
@version = '1.5', @version_date = '20200501';

Running 
SELECT TOP 1000 * FROM dbo.HumanEvents_Blocking;

Ouput:
Msg 530, Level 16, State 1, Line 2
The statement terminated. The maximum recursion 100 has been exhausted before statement completion.

Running the following works fine:
select top 1000 * from dbo.[eeper_HumanEvents_blocking

SQL Server 2019 Development CU4

**Comment by erikdarlingdata** [comment]
I have a fix for this. Can you grab the version in the dev branch? Thanks.

**Comment by tpbrownec** [comment]
I'll do that

**Comment by tpbrownec** [comment]
Installed new version of SP
deleted the view: dbo.HumanEvents_Blocking;
ran 
EXEC sp_HumanEvents @output_database_name = N'HumanEvents', @output_schema_name = N'dbo';
new version of view was created.

Query still fails!

**Comment by erikdarlingdata** [comment]
Hm, weird. The fix is here. I definitely know what you're talking about.

https://github.com/erikdarlingdata/DarlingData/commit/84581a68e4da82fd664e2632687721335336ad7a#diff-bcf3f7d484f6222d3a4ba16693ba0bfe

If you can, make sure you've got the right view version by checking the definition. It should start like this:

```
    WITH pablo_blanco
      AS (
         SELECT DISTINCT
                b.event_time,
                b.object_id,
                b.transaction_id,
                b.monitor_loop,
                b.spid,
                b.ecid,
                b.activity
         FROM [dbo].keeper_HumanEvents_blocking AS b
         WHERE b.activity = N'blocking'
```

The most important thing being the where clause at the end

Then you should see this below:

```
                 FROM [dbo].keeper_HumanEvents_blocking AS b
                 JOIN pablo_blanco AS p
                     ON  p.event_time = b.event_time
                     AND p.object_id = b.object_id
                     AND p.monitor_loop = b.monitor_loop
                     AND p.spid <> b.spid
                 WHERE b.activity = N'blocked'
```

If you don't see those, you've got the wrong version. If you do see those, you're gonna have to hit me up with repro data so I can take a closer look.

Thanks!

**Comment by tpbrownec** [comment]
As far as I can tell that matches.  What should I send you? 
The keeper_HumanEvents_blocking table has only 460 rows

PS:  I'm just trying this out.  No urgency here. But I like what you are doing!

**Comment by tpbrownec** [comment]
Also, the changes as listed in your commit are in my version

**Comment by erikdarlingdata** [comment]
Ah, okay, sorry about that. 

If you can, send me the table data in an Excel file, just without the longer text data like query text and the blocked process report XML. 

Thanks!

**Comment by tpbrownec** [comment]
Here is the data attached
[HumanEvents_sampledata.xlsx](https://github.com/erikdarlingdata/DarlingData/files/4665821/HumanEvents_sampledata.xlsx)

**Comment by erikdarlingdata** [comment]
Got it, thanks! I'll take a look soon.

**Comment by erikdarlingdata** [comment]
First, you have some very weird blocking going on. If you look at:
`SELECT * FROM keeper_HumanEvents_blocking ORDER BY id;`
It's a bunch of crazy system stuff. 

Second, I totally ate it on my recursive CTE. It worked fine on the blocking demos I have, but yours created an infinite loop. I don't see an easy way to fix that, and I don't want to keep hitting it.

There's a new version in the dev branch that creates a much simpler view with no recursion. It's not as cool as the recursive version for simpler blocking scenarios, but cool didn't get me very far anyway.

Thanks for letting me know about this.

**Comment by tpbrownec** [comment]
Yeah, I was trying to figure out why my create database was failing.  Turns out that the script I was running to find fragmentation in a database locked 'model'.

**Comment by erikdarlingdata** [comment]
That'll teach you to go looking for fragmentation 😃

**Comment by tpbrownec** [comment]
Its all using stackoverflow...just learning how stuff works.  

Thanks for looking at this
