### ISSUE TITLE
My favorite [sp_QuickieStore] is giving an error when used with Azure SQL Database

### ISSUE THREAD

**Issue by AbhinavTiwariDBA** [erikdarlingdata/DarlingData#391]
**Is your feature request related to a problem? Please describe.**
I am big fan of you, however, when I had to work on Azure SQL DB, the sp_QuickieStore gives an error

Error:
Msg 208, Level 16, State 1, Procedure sp_QuickieStore, Line 1133 [Batch Start Line 0]
Invalid object name 'sys.dm_hadr_availability_replica_states'.

**Describe the solution you'd like**
Declare one more Variable , say, @azurecheck and bypass the original logic of  if we are in Azure SQL DB.

Original Code which gives error
AND   NOT EXISTS
(
    SELECT 
        1/0
    FROM sys.dm_hadr_availability_replica_states AS s
    JOIN sys.availability_databases_cluster AS c
      ON  s.group_id = c.group_id 
      AND d.name = c.database_name
    WHERE s.is_local <> 1
    AND   s.role_desc <> N'PRIMARY'
    AND   DATABASEPROPERTYEX(c.database_name, N'Updateability') <> N'READ_WRITE'
)

**Describe alternatives you've considered**
I have modified the  original code to this for Azure SQL DB

IF @azure = 1
BEGIN
    -- Logic specific to Azure SQL Database
    INSERT INTO #databases WITH(TABLOCK)
    (
        database_name
    )
    SELECT
        database_name = ISNULL(@database_name, DB_NAME())
    WHERE @get_all_databases = 0

    UNION ALL

    SELECT
        database_name = d.name
    FROM sys.databases AS d
    WHERE @get_all_databases = 1
    AND d.is_query_store_on = 1
    AND d.database_id > 4
    AND d.state = 0 
    AND d.is_in_standby = 0 
    AND d.is_read_only = 0
    OPTION(RECOMPILE);
END
ELSE
BEGIN
    -
    INSERT INTO #databases WITH(TABLOCK)
    (
        database_name
    )
    SELECT
        database_name = ISNULL(@database_name, DB_NAME())
    WHERE @get_all_databases = 0

    UNION ALL

    SELECT
        database_name = d.name
    FROM sys.databases AS d
    WHERE @get_all_databases = 1
    AND d.is_query_store_on = 1
    AND d.database_id > 4
    AND d.state = 0 
    AND d.is_in_standby = 0 
    AND d.is_read_only = 0
    AND NOT EXISTS
    (
        SELECT 1/0
        FROM sys.dm_hadr_availability_replica_states AS s
        JOIN sys.availability_databases_cluster AS c
          ON s.group_id = c.group_id 
          AND d.name = c.database_name
        WHERE s.is_local <> 1
        AND s.role_desc <> N'PRIMARY'
        AND DATABASEPROPERTYEX(c.database_name, N'Updateability') <> N'READ_WRITE'
    )
    OPTION(RECOMPILE);
	END

**Are you ready to build the code for the feature?**
Yes.

**Comment by erikdarlingdata** [comment]
Thanks for reporting this! I'll keep an eye out for the pull request.

**Comment by AbhinavTiwariDBA** [comment]
Done, created it. I did it for the first time. thanks Erik

**Comment by AbhinavTiwariDBA** [comment]
I did that

**Comment by erikdarlingdata** [comment]
@AbhinavTiwariDBA thanks! It looks like the stuff from you fork of main is making for a somewhat odd set of changes: https://github.com/erikdarlingdata/DarlingData/pull/393/files

If you don't mind, I'm going to grab your original code change and add it to the dev branch manually. I think that'd be easier than the two of us wrestling with GitHub any more today 😃

**Comment by AbhinavTiwariDBA** [comment]
Yes please do that. Thanks a ton. I am attaching the modified code too.

[sp_QuickieStore.txt](https://github.com/erikdarlingdata/DarlingData/files/14826140/sp_QuickieStore.txt)
