### ISSUE TITLE
Question regarding sp_pressure detector sp

### ISSUE THREAD

**Issue by UriDimant** [erikdarlingdata/DarlingData#411]
Hi Erik,
Thank you for the update, I am using these procedures every day at work and it has been saved lots of problem to us. One question
My server is up time shows 12 hour (correct ) but in columns hours_cpu_time and hours_wait_time I see
35.49 and 53.6 , does it means 35 hours?
Can you clarify please?

**Comment by erikdarlingdata** [comment]
I’m not exactly sure what’s unclear, so I’m going to guess that you’re confused about those numbers being higher than uptime? Or is it something else?

**Comment by erikdarlingdata** [comment]
Because you have more than one CPU.

**Comment by erikdarlingdata** [comment]
Great, so multiple CPUs servicing multiple concurrent queries (some may be parallel) can bump those numbers up much higher than uptime.
