### ISSUE TITLE
Error at line 2021 when running with @event_type = 'blocking'

### ISSUE THREAD

**Issue by grahamfurner** [erikdarlingdata/DarlingData#42]
**Version of the script**
1.5

**What is the current behavior?**
The following error is thrown:
Msg 205, Level 16, State 1, Procedure dbo.sp_HumanEvents, Line 2021 [Batch Start Line 1]
All queries combined using a UNION, INTERSECT or EXCEPT operator must have an equal number of expressions in their target lists.

*Cause:*
The column `sqlhandle` is missing from the `INSERT INTO #blocking` statement.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run
`EXEC dbo.sp_HumanEvents @event_type = 'blocking', @seconds_sample = 1,  @database_name = '{aDatabase}';`
Replacing {aDatabase} with the name of any available database

**What is the expected behavior?**
The sproc should not error out and should report on any blocked queries as per the documentation.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Tested (and reproduced) on Windows Server 2019 with SQL 15.0.4033.1

**Comment by erikdarlingdata** [comment]
Great catch, thanks! I'll have this fixed ASAP.

**Comment by grahamfurner** [comment]
Thanks. I love this script btw.
