### ISSUE TITLE
Help error message on running sp_HumanEvents

### ISSUE THREAD

**Issue by tpbrownec** [erikdarlingdata/DarlingData#43]
I run this using latest version in master:
EXEC sp_HumanEvents @output_database_name = N'HumanEvents', @output_schema_name = N'dbo';
  
and the messages tab has this at the end:

Generating insert table statement for keeper_HumanEvents_query
Msg 50000, Level 16, State 1, Procedure sp_HumanEvents, Line 3049 [Batch Start Line 5]
 
Msg 248, Level 16, State 1, Line 6
The conversion of the nvarchar value '8918235844' overflowed an int column.

Is this fixed in dev?

**Comment by erikdarlingdata** [comment]
No, I've not run into that one. Can you provide a little more detail by either telling me which events you're logging data for, or using `@debug = 1` so I can narrow down which event session/table needs to use a `BIGINT` instead of an `INT`?

**Comment by tpbrownec** [comment]
I changed cpu_time on line 2717 to BIGINT and the error went away.

Now I want to see what the query was that caused that!

**Comment by tpbrownec** [comment]
The problem appears to be the HumanEvents job!  It ran for 10 hours the other day.  The cpu number was from THAT job!  

Need to think about skipping jobs/procs that are designed to run 'permanently'
The job i used was the one in github.  It has a schedule name of "sp_HumanEvents: 10 second Check In" but is set to run once a week.  

I going to play with that...

**Comment by tpbrownec** [comment]
The logginig Job uses about 50% of one core as long as it is running...

**Comment by erikdarlingdata** [comment]
I'm not sure what to do with this information. It runs every 5 seconds, so:
 * Should it run less often? 
 * Did you spot a tuning opportunity?
 * What's your expectation for how much CPU it should use?

I get an email every time you post a comment here. I appreciate the feedback, but please make sure you're clear about what you want to happen so I can prioritize fixes. 

Thanks,
Erik

**Comment by tpbrownec** [comment]
Sorry about the chatter, but what I really need here is a chat channel. 

The only 'fix' at this point is to change that cpu_time to BIGINT.

Everything else is just observations that I'm documenting.  That's why I didn't put this in Bug or feature when originally posted (but you did change it to bug)....When I have a concrete suggestion, I'll add one or the other to issues.

Thanks for being patient...
