### ISSUE TITLE
sp_QuickieStore: Do we have any interest in replicating the 'Queries With High Variation' dashboard?

### ISSUE THREAD

**Issue by ReeceGoding** [erikdarlingdata/DarlingData#447]
**Is your feature request related to a problem? Please describe.**
I'm mostly looking to start a discussion for this one.

In Query Store, we have the 'Queries With High Variation' dashboard. It is documented [here](https://learn.microsoft.com/en-us/sql/relational-databases/performance/best-practice-with-the-query-store?view=sql-server-ver16#start-with-query-performance-troubleshooting). I find that I almost never use it. Is there any interest in replicating it in `sp_QuickieStore`?

**Describe the solution you'd like**
The lazy solution of just adding it as an extra `@sort_order` is tempting. Just sort by the standard deviation of the duration and call it a day.

**Describe alternatives you've considered**
I think that to do it properly, we'd need a new parameter that interacts with `@sort_order`. For example, let's say we called it `@sort_by_variance_mode` and made it a boolean. When true, it would cause us to sort by the standard deviation of the metric selected by `@sort_order` rather than the metric itself.

We might not even have to compute the standard deviation. It's already in [one of the DMVs](https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-query-store-runtime-stats-transact-sql?view=sql-server-ver16). 

**Are you ready to build the code for the feature?**
If someone can convince me it's valuable, yes. It sounds like an interesting problem and I could do with the excuse to dust off my statistician's hat.

**IMPORTANT: If you're going to contribute code, please read the contributing guide first.**
https://github.com/erikdarlingdata/DarlingData/blob/main/CONTRIBUTING.md
Sure.

**Comment by erikdarlingdata** [comment]
> I find that I almost never use it. Is there any interest in replicating it in sp_QuickieStore?

Heh, I don't think I'd want to replicate a feature that neither of us use (to be honest, I've never come across anyone using it, but I am in a bit of a bubble). I sort of hate that view because the variance doesn't ever seem to be all that big, and you can find the big ones just looking at top resource consuming queries usually.

The regressed queries view would be more interesting, potentially, but also a lot more work to get right. The built in view will go and warn you about queries where there's a 100ms difference between plans, which isn't valuable.

**Comment by ReeceGoding** [comment]
Funny that you mention the regressed queries view. I've just opened an issue for it #448 . If we both agree that regressed queries is so much more worthwhile that it makes the variation dashboard useless, then feel free to just close this.
