### ISSUE TITLE
Why do we both check if @sort_order is tempdb and if @new = 1? If we know @sort_order then we know @new.

### ISSUE THREAD

**Issue by ReeceGoding** [erikdarlingdata/DarlingData#461]
**Which script is your question about?**

`sp_QuickieStore`

**Script version**

The current main branch.

**Is your question about how they work, or the results?**

Yes.

**Okay, what's your question?**

Consider [this line](https://github.com/erikdarlingdata/DarlingData/blob/main/sp_QuickieStore/sp_QuickieStore.sql#L4490C6-L4490C108)
```sql
CASE @sort_order
[...]
WHEN 'tempdb' THEN CASE WHEN @new = 1 THEN N'qsrs.avg_tempdb_space_used' ELSE N'qsrs.avg_cpu_time' END
```
Why do we check two conditions here? If `@new` isn't 1, then we hit [this condition](https://github.com/erikdarlingdata/DarlingData/blob/main/sp_QuickieStore/sp_QuickieStore.sql#L2163)
```sql
IF
(
    @sort_order = 'tempdb'
AND @new = 0
)
BEGIN
   RAISERROR('The sort order (%s) you chose is invalid in product version %i, reverting to cpu', 10, 1, @sort_order, @product_version) WITH NOWAIT;

   SELECT
       @sort_order = N'cpu';
END;
```
which changes `@sort_order` to not be `'tempdb'`. I therefore can't imagine why we need to check both `@sort_order = 'tempdb'` and `@new = 1`.

**Comment by erikdarlingdata** [comment]
@ReeceGoding I don't recall on this, sorry. I think I had written the queries to do what I wanted before I had written in any of the procedure checks. I don't think it's hurting anything, though. I'm going to leave this as-is for now with all the other changes going in though.
