### ISSUE TITLE
Why I see two poolid?

### ISSUE THREAD

**Issue by UriDimant** [erikdarlingdata/DarlingData#462]
EXEC sp_PressureDetector
    @what_to_check = 'memory',@skip_perfmon=1;
![image](https://github.com/user-attachments/assets/6a4ab2c2-3a23-4219-b39d-19312e79fad2)

Hello Erik
First of all I would like to thank for your overall contribution to the community and especially for  sp_PressureDetector stored procedure, you cannot imagine how much work it did save me in day by day at work, 

I am running this sp on the four servers and only one shows me two pools (1 and 2) , why it is so.?.. Default and internal.... 

Can you please explain?

**IMPORTANT: If you're going to contribute code, please read the contributing guide first.**
https://github.com/erikdarlingdata/DarlingData/blob/main/CONTRIBUTING.md

**Comment by erikdarlingdata** [comment]
@UriDimant hello! Seeing more than one pool is normal. Make sure all the scripts are on the same version, and you're executing them all from where the latest version will be referenced. I used to limit what showed here.

**Comment by UriDimant** [comment]
Hello Erik
EXEC sp_PressureDetector
    @what_to_check = 'memory',@skip_perfmon=1;
Yep, I am on the latest version..  It is a little bit confusing , for example max_target_memory  is the same but target_memory 
 different, can you please explain why it is so.,....

**Comment by erikdarlingdata** [comment]
@UriDimant all those values come from [sys.dm_exec_query_resource_semaphores](https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-query-resource-semaphores-transact-sql?view=sql-server-ver16), which has pretty clear definitions on all the columns.

**Comment by UriDimant** [comment]
Thank you .
