### ISSUE TITLE
HTML Code needed to put logs into a table

### ISSUE THREAD

**Issue by charlene-gif** [erikdarlingdata/DarlingData#464]
Hi @erikdarlingdata ,

Thank you for a great script to look for errors in the error logs.
I have configured an azure alert but need the correct html code to have the data be presented in a readable format.

Are you able to confirm the table names i should use for my HTML code?
Here's a bit of the code i started putting together - which i know is not right :-(:

Declare @count INT = 1
While @count <= (select MAX(IdCounter) from #errors)

BEGIN
SET
	@MAIL_BODY = (Select @Mail_Body +
	'<td>' + CONVERT(VARCHAR(10),TableID)+ '</td>'+
	'<td>' + CONVERT(VARCHAR(10),log_date)+ '</td>'+
	'<td>' + CONVERT(VARCHAR(10),process_info)+ '</td>'+
	'<td>' + CONVERT(VARCHAR(10),text)+ '</td>'+
	'</tr>'
From
dbo.#errors where IdCounter = @count )
	Set @count = @count = 1
end

**Comment by erikdarlingdata** [comment]
@charlene-gif if you run `sp_Logunter @debug = 1;` it will select temp table contents with the table name as the first column. That should get you on the right track. Thanks!
