### ISSUE TITLE
Intermittent Error "Name cannot begin with the '>' character

### ISSUE THREAD

**Issue by netsec4u** [erikdarlingdata/DarlingData#482]
**Version of the script**
    @version = '4.9',
    @version_date = '20240915';

**What is the current behavior?**
Executing with the default options, intermittent throws the error in the screenshot.

![Error](https://github.com/user-attachments/assets/5d639893-7e2e-41d5-b13e-50fe0b4780d6)

**If the current behavior is a bug, please provide the steps to reproduce.**
Below is the how the procedure is executed.  There are unknown conditions to result in the error.
`
DECLARE	@return_value int,
		@version varchar(5),
		@version_date datetime

EXEC	@return_value = [dbo].[sp_PressureDetector]
		@version = @version OUTPUT,
		@version_date = @version_date OUTPUT
`

**What is the expected behavior?**
Should not throw error.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2017 on Windows Server

**IMPORTANT: If you're going to contribute code, please read the contributing guide first.**
https://github.com/erikdarlingdata/DarlingData/blob/main/CONTRIBUTING.md

**Comment by erikdarlingdata** [comment]
@netsec4u it sounds like you might have table or index names with weird characters in them. There are a few places that use FOR XML PATH where that can happen.  If I had to bet, maybe you have an index with the default missing index name in it [<name of missing index, sysname>]. Can you try to validate that? It’ll make my debugging life a bit easier.

**Comment by netsec4u** [comment]
It is a good thing that I checked instead of going with my gut feeling.  All tables are named with alpha-numeric and underscores.  Indexes have these characters, but there are some that have periods in them.

**Comment by erikdarlingdata** [comment]
@netsec4u okay, great, if you can isolate which query threw the error, and then which column(s) are causing the problem, I can fix it.

**Comment by netsec4u** [comment]
Unfortunately, I do not know.  I was in firefighting mode where I just took a screenshot of the error to review later and rerun the procedure.  I am working on a performance issue that is more noticeable on Monday's and Tuesday's.  But I will periodically run this procedure and let you know when I am able to duplicate.

**Comment by erikdarlingdata** [comment]
@netsec4u okay, cool. You may want to run it with `@debug = 1` to help figure out the problem. I'll leave this open for a bit for you to come back to, but if I don't hear from you for a month, I'll close it out. I understand that these transient issues are tough. There are similar problems with [sp_WhoIsActive](https://github.com/amachanic/sp_whoisactive/issues/99) too.

**Comment by netsec4u** [comment]
Based on the warning about null values being eliminated, the error is one of the queries after the "Checking memory pressure" query.

**Comment by netsec4u** [comment]
I was able to duplicate.  Looks like the error is in the last result set that contains the active queries.
![Screenshot 2024-10-10 113125](https://github.com/user-attachments/assets/c0491fd4-71d9-40df-84c0-9084f51a3f8d)

Also, I found a way to replicate with some consistency.  Execute sp_BlitzFirst with ExpertMode set to 1, then in a second session execute sp_PressureDetector.  Looks like you can blame Brent.  Lol.

**Comment by erikdarlingdata** [comment]
@netsec4u ha ha, looks like I should add an `@IgnoreBrent` parameter to this one.

**Comment by erikdarlingdata** [comment]
@netsec4u I've got a fix coming in for this with some other stuff. It should be in soon.
