### ISSUE TITLE
sp_QuickieStore: Why are we setting @end_date_original to a value that has nothing to do with @end_date when @start_date exceeds @end_date?

### ISSUE THREAD

**Issue by ReeceGoding** [erikdarlingdata/DarlingData#484]
**Which script is your question about?**

sp_QuickieStore

**Script version**

The current dev version.

**Is your question about how they work, or the results?**

How it works.

**Okay, what's your question?**

I recently found [this block](https://github.com/erikdarlingdata/DarlingData/blob/dev/sp_QuickieStore/sp_QuickieStore.sql#L1784) while tweaking my regression stuff.

```sql
/*
I need to tweak this so the WHERE clause on the last execution column
works correctly as >= @start_date and < @end_date, otherwise there are no results
*/
IF @start_date >= @end_date
BEGIN
    SELECT
        @end_date =
            DATEADD
            (
                DAY,
                7,
                @start_date
            ),
        @end_date_original =
            DATEADD
            (
                DAY,
                1,
                @start_date_original
            );
END;
```

Why are we setting `@end_date_original` to a value that has nothing to do with `@end_date` when `@start_date` exceeds `@end_date`?

**IMPORTANT: If you're going to contribute code, please read the contributing guide first.**
https://github.com/erikdarlingdata/DarlingData/blob/main/CONTRIBUTING.md
Sure.

**Comment by erikdarlingdata** [comment]
@ReeceGoding read the code carefully. It’s protecting against cases where start date is after end date.
