### ISSUE TITLE
sp_QuickieStore: Several of the parameters don't appear in the example file.

### ISSUE THREAD

**Issue by ReeceGoding** [erikdarlingdata/DarlingData#489]
**Is your feature request related to a problem? Please describe.**
A pet peeve of mine is having parameters that aren't in the [documentation's list of examples](https://github.com/erikdarlingdata/DarlingData/blob/dev/sp_QuickieStore/Examples.sql). Currently, the following are in the `@help = 1` text but not the examples:

- Various possible values of `@execution_type_desc`
- `@procedure_schema`
- `@timezone`
- `@query_type`
- `@query_text_search_not`
- `@hide_help_table`
- `@ignore_query_hashes`
- `@ignore_plan_hashes`
- `@ignore_sql_handles`
- `@workdays`
- `@work_start`
- `@work_end`
- Lots of the `@sort_order` values
- `@escape_brackets`
- `@escape_character`
- `@only_queries_with_feedback`
- `@only_queries_with_variants`
- `@only_queries_with_forced_plans`
- `@only_queries_with_forced_plan_failures`
- `@get_all_databases`
- `@version`
- `@version_date`.

Furthermore, the following are in `@help = 1` but not [the readme](https://github.com/erikdarlingdata/DarlingData/tree/dev?tab=readme-ov-file#quickie-store):

- `@query_text_search_not`
- `@hide_help_table`
- Lots of the `@sort_order` values.

**Describe the solution you'd like**
Write up some examples and typical use cases, then add them in.

**Describe alternatives you've considered**
Self-pity. A few of these are my fault!

**Are you ready to build the code for the feature?**
Probably, but I don't know if I can be bothered to spin up a 2022 box just for the sake of getting familiar with the parameters exclusive to that. 

**IMPORTANT: If you're going to contribute code, please read the contributing guide first.**
https://github.com/erikdarlingdata/DarlingData/blob/main/CONTRIBUTING.md
Yep.

**Comment by erikdarlingdata** [comment]
@ReeceGoding yes, keeping up with the documentation is an admin task that I don't do a great job with. It seems to only happen in avalanches. Anything you want to do in here is appreciated.

**Comment by erikdarlingdata** [comment]
@ReeceGoding should this be closed as well?

**Comment by ReeceGoding** [comment]
@erikdarlingdata No. The recent merge made a tiny dent in it while documenting the regression stuff, but it didn't touch the vast majority of the stuff here.
