### ISSUE TITLE
sp_Quickiestore: How about @sort_order = 'rows'?

### ISSUE THREAD

**Issue by ReeceGoding** [erikdarlingdata/DarlingData#498]
**Is your feature request related to a problem? Please describe.**
I've often heard it said that there is no good reason for your users to grab millions of rows from your server. Let's add a feature to `sp_Quickiestore` to find such cases:  `@sort_order = 'rows'`.

**Describe the solution you'd like**
We already return `avg_rowcount`, `total_rowcount`, and `max_rowcount`, as well as some others in expert mode. They come from the same table as things that we've always sorted by, like cpu. Adding these on as an extra sort order should be super easy. I'd probably just make `@sort_order = 'rows'` sort by `avg_rowcount`.

**Describe alternatives you've considered**
Give more than one new `@sort_order`, e.g. 'total rows' and 'max rows'.

**Are you ready to build the code for the feature?**
I'm reluctant. I thought that I was free of adding new stuff to this...

**IMPORTANT: If you're going to contribute code, please read the contributing guide first.**
https://github.com/erikdarlingdata/DarlingData/blob/main/CONTRIBUTING.md
Sure.

**Comment by erikdarlingdata** [comment]
Closed via #501
