### ISSUE TITLE
There are too many executions 

### ISSUE THREAD

**Issue by micke314** [erikdarlingdata/DarlingData#51]
**Version of the script**
SELECT @version = '1.5', @version_date = '20200501';

**What is the current behavior?**
With event_type query the number of executions is counted twice.

**If the current behavior is a bug, please provide the steps to reproduce.**
Start sp_HumanEvents with @event_type = 'query', @gimme_danger = 1
Quickly jump to another tab and run a query three times, no more no less. Three shall be the number thou shalt execute, and the number of the executing shall be three.

**What is the expected behavior?**
The number of executions reported by sp_HumanEvents should be three.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2019

**Comment by micke314** [comment]
I tried to fix it in a fork that you can use if you like it https://github.com/micke314/DarlingData

**Comment by erikdarlingdata** [comment]
Can you pretty please confirm that you've pulled the newest version down to your repo? The compare looks a little funny.

https://github.com/erikdarlingdata/DarlingData/compare/master...micke314:master

**Comment by micke314** [comment]
Yes, I did.
First I fixed it.
Then I removed the use of a temp table that, in my humble opinion, was not necessary anymore.
And since then I have pulled your changes to master into my fork

**Comment by erikdarlingdata** [comment]
Awesome, thanks! I'll take a look this morning.

**Comment by erikdarlingdata** [comment]
looks good, thanks! merging in.
