### ISSUE TITLE
sp_HumanEvents - Output Query

### ISSUE THREAD

**Issue by pricewise987** [erikdarlingdata/DarlingData#53]
sp_HumanEvents

Current version (updated yesterday)

Hi Erik

Great shout out from Brent today on these scripts

"Live Coding T-SQL with Microsoft SQL Server" on Twitch

I'm trying to figure out where the difference is

Same version of sp_HumanEvents and StackOverflow

I get a different output to Brent (story of my life....!!)

See screen shots below

Any idea why they would be different -apologies if this is blindingly obvious

Cheers Erik

Love your stuff

![Human_Events_Brent](https://user-images.githubusercontent.com/64111183/84578330-25ed7f80-adbc-11ea-9a53-b56ab0d3be1d.jpg)

![Human_Events_Me](https://user-images.githubusercontent.com/64111183/84578333-2ab23380-adbc-11ea-9362-9cdc0e20f4d0.jpg)

**Comment by erikdarlingdata** [comment]
It looks like you're using an older version of SQL Server that doesn't support the same events as what brent has. Can you confirm what `SELECT @@VERSION;` returns?

**Comment by pricewise987** [comment]
BINGO
Thanks a mill Erik
Ran it on SQL 2019 Developer edition - perfection
Absolutely love PressureDetector and HumanEvents - my new GO-TO scripts.
Looking forward to your next Live stream.
Thank again Erik
Stay Safe
Cathal
    On Saturday, 13 June 2020, 21:36:18 GMT+1, Erik Darling <notifications@github.com> wrote:  
 
 


It looks like you're using an older version of SQL Server that doesn't support the same events as what brent has. Can you confirm what SELECT @@VERSION; returns?

**Comment by erikdarlingdata** [comment]
There you go! Hope that gets you on your way. Thanks!

**Comment by pricewise987** [comment]
Hi Erik
Attached is an Azure Database Compatible Version of sp_PressureDetector.
If you comment out the DAC-enabled check it works perfectly.
Thanks again for these - brilliant scripts to have.
Cathal

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
