### ISSUE TITLE
sp_HumanEvents error handling - transaction rollback

### ISSUE THREAD

**Issue by AdrianB1** [erikdarlingdata/DarlingData#54]
Hi, the transaction rollback part in the TRY CATCH block seems wrong. This is the current code: 
IF @@TRANCOUNT > 0 
        ROLLBACK TRANSACTION;

First, as you don't begin any transaction you should not roll back any; if there is a transaction open, it is not yours to rollback. Second, @@TRANCOUNT can be more than 1 and in that case ROLLBACK will just decrement @@TRANCOUNT by 1, but it will not do anything else. My suggestion is to leave the transaction part alone and remove this piece of code.

**Comment by erikdarlingdata** [comment]
right, thanks. it's there as sort of part of my standard try/catch template. granted it'd be a little odd to need a transaction in here, but it's not harming anything.
