### ISSUE TITLE
sp_HumanEvents raiserror/throw behavior

### ISSUE THREAD

**Issue by AdrianB1** [erikdarlingdata/DarlingData#55]
**Which script is your question about?**

Script Name: sp_HumanEvents

**Script version**

1.5

**Is your question about how they work, or the results?**
Why it does what it does

**Okay, what's your question?**

The catch block has a RAISERROR on line 3015 just before a THROW. What is the purpose of the RAISERROR in that place, to tell if there was any error in the ROLLBACK at 2986? If yes, that ROLLBACK should be in a TRY block, if not, line 3015 returns exactly the same information as the THROW, so line 3016 is either wrong or redundant.

This code shows the behavior: the ERROR_NUMBER() and other functions capture the first error in the TRY block, not the second one.

BEGIN TRY
	RAISERROR(N'first error', 16, 1) WITH NOWAIT;
END TRY
BEGIN CATCH
	DECLARE @msg NVARCHAR(2048) = N'';
	RAISERROR(N'second error', 16, 1) WITH NOWAIT;
	SELECT  @msg += N'Error number '
                 +  RTRIM(ERROR_NUMBER()) 
                 +  N' with severity '
                 +  RTRIM(ERROR_SEVERITY()) 
                 +  N' and a state of '
                 +  RTRIM(ERROR_STATE()) 
                 +  N' in procedure ' 
                 +  COALESCE(ERROR_PROCEDURE(),'') 
                 +  N' on line '  
                 +  RTRIM(ERROR_LINE())
                 +  NCHAR(10)
                 +  ERROR_MESSAGE(); 
	RAISERROR(@msg, 16, 1) WITH NOWAIT;
	THROW; 
END CATCH

**Comment by erikdarlingdata** [comment]
Hi,
Interesting question. I'm pretty sure I added the raiserror in when I was troubleshooting errors in some of the dynamic SQL, but I don't recall fully now. Here's a quick example below.

```
CREATE OR ALTER PROCEDURE dbo.handler
AS
BEGIN

    BEGIN TRY
        DECLARE @sql NVARCHAR(MAX) = N'SELECT 1/0;';
        EXEC sp_executesql @sql;
    END TRY
    
    BEGIN CATCH
        DECLARE @msg NVARCHAR(2048) = N'';

        SELECT @msg += N'Error number '
        + RTRIM(ERROR_NUMBER())
        + N' with severity '
        + RTRIM(ERROR_SEVERITY())
        + N' and a state of '
        + RTRIM(ERROR_STATE())
        + N' in procedure '
        + COALESCE(ERROR_PROCEDURE(),'')
        + N' on line '
        + RTRIM(ERROR_LINE())
        + NCHAR(10)
        + ERROR_MESSAGE();
        
        RAISERROR(@msg, 16, 1) WITH NOWAIT;
        THROW;
    END CATCH

END
GO 
```

**Comment by AdrianB1** [comment]
Even in this case, the RAISERROR and THROW are redundant because they will report the same information.

Msg 50000, Level 16, State 1, Line 22
Error number 8134 with severity 16 and a state of 1 in procedure  on line 1
Divide by zero error encountered.
Msg 8134, Level 16, State 1, Line 1
Divide by zero error encountered.

The first 3 lines come from RAISERROR, the next 2 from THROW. The very first line has no value, the others have the same info.
