### ISSUE TITLE
Azure DB/MI Detection

### ISSUE THREAD

**Issue by Mnemonic23** [erikdarlingdata/DarlingData#56]
SELECT @version = '1.5', @version_date = '20200501';

Current behavior - when running on a SQL Managed Instance, it properly detects that I'm in Azure, however, two issues immediately arise:

1 - The start commands for the event session refer to SERVER and not DATABASE as the path for Azure SQL DB should be.

2 - When in an MI (as I am), I have access to SERVER EVENTS.  When I run a version where I just force the @Azure bit to be 0, it runs perfectly fine.  

So:
* the @Start_SQL needs to be fixed so that if the event is created for database, it starts it in database.  other locations may be affected.

* Is there a way to detect if running on a Managed Instance rather than Azure SQL?  If so, should treat as if traditional.  

Lovely product, looking forward to adding this to my arsenal.

Thanks,
Jonathan

**Comment by erikdarlingdata** [comment]
I appreciate the feedback, here! I don't have a managed instance or azure sql db to test this out on. If you do, and you're willing to make a code contribution, awesome. Otherwise, I'm probably going to have to shelf compatibility with cloud stuff, because there are a lot of weird changes. 

Thanks!

**Comment by Mnemonic23** [comment]
Erik,

I put together some fixes and it now works on both my Managed Instance and
an Azure SQL DB that I had available.  I couldn't test every parameter set,
but at least it works for me.  I tried my best to do a commit back to
source.  This was my very first git-hub contribution, so please let me know
if I did something wrong or it doesn't work properly.  I'm including my
version here as well, just in case.

**Comment by erikdarlingdata** [comment]
Will do, thanks for the PR!

**Comment by leebrownhill** [comment]
Thanks so much for this fix. I ran into this issue yesterday on one of our Azure Managed Instances. 

Have just tested the fix provided by @Mnemonic23 and i can confirm that it works perfectly on the Managed Instance. The fixed version created a server level extended event and tidied up after itself too.

For others who have encountered this issue, you might want to go an tidy up the left over sessions which exist in sys.database_event_sessions however. 

Thanks again!
