### ISSUE TITLE
Would be nice to have the query text in the query plan

### ISSUE THREAD

**Issue by micke314** [erikdarlingdata/DarlingData#59]
**Is your feature request related to a problem? Please describe.**
When looking at the query plan from sp_HumanEvents, the query text is missing.

**Describe the solution you'd like**
Would be nice to have the query text in the query plan

**Describe alternatives you've considered**
You could have look in the column statement_text but ...

**Are you ready to build the code for the feature?**
Sure, just need to get friendly with GitHub

**Comment by erikdarlingdata** [comment]
You are an absolute madman.

**Comment by micke314** [comment]
Pre 2019 we still miss the attribute StatementType that makes the root operator look good. I see no reliable way of finding out what value it should have. I don't even know what possible values could be there (not specified in the schema) but I would guess (SELECT, UPDATE, DELETE, MERGE). 
It does render ok in SSMS without it and better still in Plan Explorer
