### ISSUE TITLE
requested_memory_mb error 

### ISSUE THREAD

**Issue by michaeldspain** [erikdarlingdata/DarlingData#62]
Msg 50000, Level 16, State 1, Procedure sp_HumanEvents, Line 3105 [Batch Start Line 1]
 
Msg 25713, Level 16, State 15, Line 3
The value specified for event attribute or predicate source, "requested_memory_kb", event, "query_post_execution_showplan", is invalid.

EXEC dbo.sp_HumanEvents @event_type = 'query', @query_duration_ms = 1000, @seconds_sample = 20, @requested_memory_mb = 1024;

Microsoft SQL Server 2016 (SP2-CU11) (KB4527378) - 13.0.5598.27 (X64) 
	Nov 27 2019 18:09:22 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by erikdarlingdata** [comment]
This is fixed now, thanks for letting me know.
