### ISSUE TITLE
Problem collecting from XE QUERY "too many levels"

### ISSUE THREAD

**Issue by Zhunya** [erikdarlingdata/DarlingData#67]
**Version of the script**
Latest

**What is the current behavior?**
SQL Agent collection job fails

Generating insert table statement for keeper_HumanEvents_query 
[SQLSTATE 01000] (Message 50000)  Error number 6335 with severity 16 and a state of 101 in procedure sp_HumanEvents on line 2896 XML datatype instance has too many levels of nested nodes. Maximum allowed depth is 128 levels. 
[SQLSTATE 42000] (Error 50000)  XML datatype instance has too many levels of nest...  The step failed.

**If the current behavior is a bug, please provide the steps to reproduce.**
I don't know how to reproduce this behavior.

**What is the expected behavior?**
Just run and fill tables with monitored data

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)   Feb 15 2020 01:47:30   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by erikdarlingdata** [comment]
Ah yeah, that's a limitation with SQL Server. Nothing I can do about it at the moment. It may be a case where I could use TRY_CONVERT, but not only is that just for 2016+, but databases have to be in compat level 130 or higher. It's gonna be a while before that's widespread enough to adopt. Thanks though!
