### ISSUE TITLE
sp_HumanEvents - Azure SQL Database DMV Error

### ISSUE THREAD

**Issue by MoochingTusk** [erikdarlingdata/DarlingData#75]
**Version of the script**
SELECT @version = '1.5', @version_date = '20200501';

**What is the current behavior?**
Several errors when running sp_HumanEvents in Azure SQL Database

**If the current behavior is a bug, please provide the steps to reproduce.**
EXEC [dbo].[sp_HumanEvents] @event_type = 'query',
                            @query_duration_ms = 1000,
                            @database_name = 'MyDB',
                            @keep_alive = 1;

EXEC sp_HumanEvents @output_database_name = N'MyDB', @output_schema_name = N'log';

/*
The first statement works fine and the event starts. However the second errors due to numerous references to sys.server_event_sessions, which I believe should be sys.database_event_sessions for Azure DB. There are also invalid references to dm_xe_database_session_targets and dm_xe_database_session. 

Msg 208, Level 16, State 1, Procedure sp_HumanEvents, Line 2140 [Batch Start Line 6]
Invalid object name 'sys.server_event_sessions'.
*/
**What is the expected behavior?**
It appears that the @Azure parameter needs checking in these additional places and alternate statements
written. I quickly modified all references in my version 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Azure SQL Database

**Comment by erikdarlingdata** [comment]
Hi there! Thanks for letting me know. Is this code you were going to work on and submit a PR for?

I don't have Azure stuffs to test on -- the [previous commits to make it Azure compatible were from someone else](https://github.com/erikdarlingdata/DarlingData/pull/57/commits/72287758890199032c09f713ad5696c536bd77da) -- so I don't have a good way to fix things. 

Lemme know!

Thanks,
Erik

**Comment by MoochingTusk** [comment]
Hi Erik,

Yes I will, but it may be a week or so before I get to it, so thought I'd raise an issue first. I initially did a simple text find and replace (just to test obviously) but the output table ([keeper_HumanEvents_query]) was empty, so it may not be quite as straightforward as I'd hoped.

Will submit a PR when it's done. Thanks.

**Comment by erikdarlingdata** [comment]
Cool, thanks! Looking forward to it!

**Comment by erikdarlingdata** [comment]
Checking back in -- did you still want to work on this?

**Comment by MoochingTusk** [comment]
Hi Eric. Yes definitely it’s still on my list. Work stuff has taken over but should get to it next week.

**Comment by MoochingTusk** [comment]
PR submitted. This is the first time I've submitted a PR so forgive me if I've not followed the right process. Tried to do as much research as I could!

**Comment by erikdarlingdata** [comment]
Looks good, thanks!
