### ISSUE TITLE
sp_PressureDetector: Add statement_start_offset to facilitate creation of plan guides

### ISSUE THREAD

**Issue by L3onard80** [erikdarlingdata/DarlingData#78]
Hi Erik, thanks for the very useful sproc.

Would it be possible to have the column in subject to the right of the **plan_handle** column? 
It would make creating plan guides much more convenient.

![image](https://user-images.githubusercontent.com/63165379/107859707-982ace00-6e3b-11eb-8a6a-4f0816a50046.png)

Thanks for the attention.

**Comment by erikdarlingdata** [comment]
Er... which proc are you referring to?

**Comment by L3onard80** [comment]
pff... sorry sp_PressureDetector

**Comment by erikdarlingdata** [comment]
Sure, that should be easy!

**Comment by L3onard80** [comment]
> Sure, that should be easy!

Cool!!
