### ISSUE TITLE
String mangling of @seconds_sample for WAITFOR DELAY 

### ISSUE THREAD

**Issue by wqweto** [erikdarlingdata/DarlingData#83]
This works here

```
DECLARE @seconds_sample INTEGER = 100
DECLARE @waitfor NVARCHAR(20)

SELECT @waitfor = CONVERT(NVARCHAR(20), DATEADD(s, @seconds_sample, 0), 114)
WAITFOR DELAY @waitfor
```

**Comment by erikdarlingdata** [comment]
@wqweto can you be a little bit more specific about what you'd like me to do with this? Thanks!

**Comment by wqweto** [comment]
I was reading [this snippet](https://github.com/erikdarlingdata/DarlingData/blob/master/sp_HumanEvents/sp_HumanEvents.sql#L819-L859) and thought it seemed a bit overcomplicated.

Could be I misunderstand the intent and the needed result in `@waitfor` though.

**Comment by erikdarlingdata** [comment]
Oh that is cool! If you wanna do a PR for it, be my guest.

**Comment by erikdarlingdata** [comment]
Thank you!
