### ISSUE TITLE
sp_pressure_detector

### ISSUE THREAD

**Issue by sm8680** [erikdarlingdata/DarlingData#9]
SELECT @version = '1.0', @versiondate = '20200301';

For versions of SQL Server if they don't have the following 2 columns.  
deqmg.reserved_worker_count and deqmg.used_worker_count

The following error message occurs.  
Msg 102, Level 15, State 1, Line 18
Incorrect syntax near '.'.
Msg 156, Level 15, State 1, Line 24
Incorrect syntax near the keyword 'ORDER'

Consider Changing the placement of the ,

                waits.wait_type'
                + CASE WHEN @helpful_new_columns = 1
                       THEN N',
                deqmg.reserved_worker_count,
                deqmg.used_worker_count,'
                       ELSE N''
                END

to

                waits.wait_type,'
                + CASE WHEN @helpful_new_columns = 1
                       THEN N'
                deqmg.reserved_worker_count,
                deqmg.used_worker_count,'
                       ELSE N''
                END

**Comment by erikdarlingdata** [comment]
Done, thanks!
