### ISSUE TITLE
arithmetic overflow error for type int

### ISSUE THREAD

**Issue by TheDBAYogi** [erikdarlingdata/DarlingData#94]
**Version of the script**
20200501

**What is the current behavior?**
arithmetic overflow error for type int when insert into keeper_HumanEvents_blocking

**If the current behavior is a bug, please provide the steps to reproduce.**
This only happens on an extraordinarily busy server, I think the transactionID is greater than the int range

**What is the expected behavior?**
As discussed

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2017 Windows 2016. This is my first attempt to use this
if I change the int to Bigint for transaction_id  then everything will work. for table keeper_HumanEvents_blocking
N'  transaction_id BIGINT NULL, resource_owner_type NVARCHAR(256) NULL, monitor_loop INT NULL, spid INT NULL, ecid INT NULL, query_text NVARCHAR(MAX) NULL, ' +

**Comment by erikdarlingdata** [comment]
Fair! I can make this change easily.
